#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# If the ${HOME}/.dev-tools is not preset, create it.
if [ ! -d "${HOME}/.dev-tools" ]; then mkdir -p "${HOME}/.dev-tools"; fi

# Check for the pre-existing repo ~> git@github.com:philipdelorenzo/pre-commit-docker.git
if [ ! -d "${HOME}/.dev-tools/pre-commit-docker" ]; then
  git clone git@github.com:philipdelorenzo/pre-commit-docker.git "${HOME}/.dev-tools/pre-commit-docker"
else
  cd "${HOME}/.dev-tools/pre-commit-docker" || exit 1 && git checkout master && git pull
fi

echo "Ensuring latest version of Docker image..."
cd "${HOME}/.dev-tools/pre-commit-docker" || exit 1 && docker build . -t philipdelorenzo/dev-tools:latest -q

# We want to run this docker image as a container in the context of the location of this file ~> ${REPO}/.githooks/*
docker run \
  -v "${DIR}/..:/src" -v "${DIR}/../.cache:/worker/.pre-commit-cache" \
  --rm philipdelorenzo/dev-tools:latest /bin/bash /worker/pre-commit.sh
