repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  additional_dependencies: ['click>=8.1.2']
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/detailyang/pre-commit-shell.git
  rev: v1.0.6
  hooks:
  - id: shell-lint
    args: [--format=json]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
